# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e0c892e11bd02c9a88dbaae1642c61026e5bfd4b4d28be03854a7d2111ffbae61cb91d157e476ba8d7f496263e5326e49c9cea83c7b8962c57440621a07934a

test:
  secret_key_base: c609bcf6cfde56e832200a67ea4a9ca4bd787a516a944f95c41715a83b0db1b2f0e656dc1d36feba76fb7e1f19764c2f09a5c78cab663362fa38b8fce50f36e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
